### PR TITLE
update to match new api for FillText

### PR DESCRIPTION
**Pull request by brentp**
required to run human.go

### CODE REVIEW

**Comment by brentp** [comment]
guess I'd better run the tests. :(

**Comment by brentp** [comment]
not clear how best to update the tests. How were those generated? Or is gonum/plot in enough flux that it's best to wait on this?

**Comment by kortschak** [comment]
Test cases are created through a relatively painfull process. I can do that.

**Comment by kortschak** [comment]
It looks one is failing on visual inspection though. The axis label on axis-0 is incorrect (it should be oriented parallel with the scale labels on that axis). I'll generate test cases when you have fixed that (use -allpic when you run the rings test). If you checkout gonum/plot at 986a404 you can get the previous behaviour for a known good state.

**Comment by brentp** [comment]
OK. Latest push makes sensible change that seems fix that issue.

**Comment by kortschak** [comment]
Updated tests are here https://gist.github.com/kortschak/2ba3e457b134fe8a9ce45f67221fd5fe

**Comment by brentp** [comment]
those tests pass.

**Comment by kortschak** [comment]
Please add them to this PR.

**Comment by brentp** [comment]
is this good-to-merge now?

**Pull request merged**
